/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as IndexRouteImport } from './routes/index'
import { Route as EmploesEmploesRouteImport } from './routes/emploes/emploes'
import { Route as EmploesEmploeIdRouteImport } from './routes/emploes/$emploeId'
import { Route as ClassClassesRouteImport } from './routes/class/classes'
import { Route as ClassClassNameRouteImport } from './routes/class/$className'
import { Route as ClassClassesNewRouteImport } from './routes/class/classes.new'

const rootRouteImport = createRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploesEmploesRoute = EmploesEmploesRouteImport.update({
  id: '/emploes/emploes',
  path: '/emploes/emploes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploesEmploeIdRoute = EmploesEmploeIdRouteImport.update({
  id: '/emploes/$emploeId',
  path: '/emploes/$emploeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassesRoute = ClassClassesRouteImport.update({
  id: '/class/classes',
  path: '/class/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassNameRoute = ClassClassNameRouteImport.update({
  id: '/class/$className',
  path: '/class/$className',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassesNewRoute = ClassClassesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClassClassesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/class/$className': typeof ClassClassNameRoute
  '/class/classes': typeof ClassClassesRouteWithChildren
  '/emploes/$emploeId': typeof EmploesEmploeIdRoute
  '/emploes/emploes': typeof EmploesEmploesRoute
  '/class/classes/new': typeof ClassClassesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/class/$className': typeof ClassClassNameRoute
  '/class/classes': typeof ClassClassesRouteWithChildren
  '/emploes/$emploeId': typeof EmploesEmploeIdRoute
  '/emploes/emploes': typeof EmploesEmploesRoute
  '/class/classes/new': typeof ClassClassesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/class/$className': typeof ClassClassNameRoute
  '/class/classes': typeof ClassClassesRouteWithChildren
  '/emploes/$emploeId': typeof EmploesEmploeIdRoute
  '/emploes/emploes': typeof EmploesEmploesRoute
  '/class/classes/new': typeof ClassClassesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/class/$className'
    | '/class/classes'
    | '/emploes/$emploeId'
    | '/emploes/emploes'
    | '/class/classes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/class/$className'
    | '/class/classes'
    | '/emploes/$emploeId'
    | '/emploes/emploes'
    | '/class/classes/new'
  id:
    | '__root__'
    | '/'
    | '/class/$className'
    | '/class/classes'
    | '/emploes/$emploeId'
    | '/emploes/emploes'
    | '/class/classes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassClassNameRoute: typeof ClassClassNameRoute
  ClassClassesRoute: typeof ClassClassesRouteWithChildren
  EmploesEmploeIdRoute: typeof EmploesEmploeIdRoute
  EmploesEmploesRoute: typeof EmploesEmploesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emploes/emploes': {
      id: '/emploes/emploes'
      path: '/emploes/emploes'
      fullPath: '/emploes/emploes'
      preLoaderRoute: typeof EmploesEmploesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emploes/$emploeId': {
      id: '/emploes/$emploeId'
      path: '/emploes/$emploeId'
      fullPath: '/emploes/$emploeId'
      preLoaderRoute: typeof EmploesEmploeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/classes': {
      id: '/class/classes'
      path: '/class/classes'
      fullPath: '/class/classes'
      preLoaderRoute: typeof ClassClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$className': {
      id: '/class/$className'
      path: '/class/$className'
      fullPath: '/class/$className'
      preLoaderRoute: typeof ClassClassNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/classes/new': {
      id: '/class/classes/new'
      path: '/new'
      fullPath: '/class/classes/new'
      preLoaderRoute: typeof ClassClassesNewRouteImport
      parentRoute: typeof ClassClassesRoute
    }
  }
}

interface ClassClassesRouteChildren {
  ClassClassesNewRoute: typeof ClassClassesNewRoute
}

const ClassClassesRouteChildren: ClassClassesRouteChildren = {
  ClassClassesNewRoute: ClassClassesNewRoute,
}

const ClassClassesRouteWithChildren = ClassClassesRoute._addFileChildren(
  ClassClassesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassClassNameRoute: ClassClassNameRoute,
  ClassClassesRoute: ClassClassesRouteWithChildren,
  EmploesEmploeIdRoute: EmploesEmploeIdRoute,
  EmploesEmploesRoute: EmploesEmploesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
